services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - cbomkit-net

  backend:
    image: cbomkit:dev-back
    environment:
      CBOMKIT_DB_TYPE: postgresql
      CBOMKIT_DB_JDBC_URL: jdbc:postgresql://db:5432/postgres
      CBOMKIT_PORT: 8081
      CBOMKIT_DB_USERNAME: ${POSTGRESQL_AUTH_USERNAME}
      CBOMKIT_DB_PASSWORD: ${POSTGRESQL_AUTH_PASSWORD}
      CBOMKIT_FRONTEND_URL_CORS: "http://localhost:8000"
    ports:
      - "8081:8081"
    volumes:
      - cbomkit-volume:/home/user/.cbomkit
    restart: always
    networks:
      - cbomkit-net
    deploy:
      resources:
        reservations:
          memory: 16g
    profiles:
      - prod
      - ext-compliance
      - dev-frontend

  frontend:
    image: cbomkit:dev-front
    environment:
      VUE_APP_HTTP_API_BASE: "http://localhost:8000/api"
      VUE_APP_WS_API_BASE: "ws://localhost:8000"
      VUE_APP_TITLE: "CBOMkit"
      VUE_APP_VIEWER_ONLY: ${CBOMKIT_VIEWER}
    restart: always
    networks:
      - cbomkit-net
    profiles:
      - prod
      - ext-compliance
      - dev-backend
      - viewer

  db:
    image: postgres:16-alpine
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRESQL_AUTH_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_AUTH_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRESQL_AUTH_USERNAME}", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-volume:/var/lib/postgresql/data/
    restart: always
    networks:
      - cbomkit-net
    profiles:
      - prod
      - ext-compliance
      - dev
      - dev-backend
      - dev-frontend

  regulator:
    image: ibm-regulator
    environment:
      OPA_BASE_URL: "http://opa:8181"
    ports:
      - "8080:8080"
    networks:
      - cbomkit-net
    profiles:
      - ext-compliance

  opa:
    image: openpolicyagent/opa:0.66.0
    command:
      - "run"
      - "--addr=0.0.0.0:8181"
      - "--server"
    ports:
      - "8181:8181"
    networks:
      - cbomkit-net
    profiles:
      - ext-compliance

volumes:
  cbomkit-volume:
  pg-volume:

networks:
  cbomkit-net:
